### ISSUE TITLE
Consultar bibliotecas de terceiros

### ISSUE THREAD

**Issue by fabiommendes** [wilkerwma/pbl_codeschool#1]
Encontrei estas duas:

* https://gamification-engine.herokuapp.com/admin/goalgoalproperty/
* https://github.com/ngageoint/gamification-server

Liste os pros/contras de cada uma em comparação com criar tudo do zero. A primeira alternativa parece mais madura, mas não roda em django, o que dificulta um pouco as coisas.

**Comment by wilkerwma** [comment]
**Gamification-Engine:**
**Pros:** Sobre a gamification-engine, não vejo muitos pros a não o fato da lógica de points and Badges já estarem implementadas. 
**Contras: ** Não rodar em Django, não possuir todas as funcionalidades esperadas para nossa aplicação e não sabermos como ela irá se comportar dentro do CodeSchool.

**Gamification-server:**
**Pros:** Ser um projeto acoplável à websites, possuir as lógicas de programação para Points, Badges and Leaderboards. 
**Contras:**  Não sabermos se apresentará o comportamento desejável dentro do codeSchool e caso não apresente qual será o custo para adaptarmos a solução à ponto de torna-la aceitável.
